# Generated by Django 4.2.1 on 2023-05-17 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fcplayers', '0002_fcplayers_age_fcplayers_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcplayers',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
